version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: TestApp.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: 7z a release.zip C:\projects\weberdownloader\bin\Release\net461\*.*
artifacts:
- path: release.zip
  name: WeberDownloader
cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
deploy:
- provider: GitHub
  auth_token:
    secure: YqenUcFU4kK7iz8nABkW4hHd2RvuJkVhagYAHMyqAOrbuvdE2AUcvnX29juiCkKU
  artifact: release.zip