version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  APPVEYOR_RDP_PASSWORD: weberdownloader123
init:
   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
- cmd: nuget restore
build:
  project: TestApp.sln
  verbosity: minimal
after_build:
  - cmd: xcopy C:\projects\weberdownloader\wwwroot\*.* C:\projects\weberdownloader\bin\Release\net461\  /sy
  - cmd: 7z a release.zip C:\projects\weberdownloader\bin\Release\net461\*.*
artifacts:
- path: release.zip
  name: WeberDownloader
cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
deploy:
- provider: GitHub
  auth_token:
    secure: YqenUcFU4kK7iz8nABkW4hHd2RvuJkVhagYAHMyqAOrbuvdE2AUcvnX29juiCkKU
  artifact: release.zip