 version: 2.1

 orbs:
  win: circleci/windows@2.4.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build --output C:\Users\circleci\project\output --configuration Release
       - run: cp -r C:\Users\circleci\project\wwwroot\ C:\Users\circleci\project\output\
       - run: Compress-Archive -Path C:\Users\circleci\project\output -DestinationPath C:\Users\circleci\project\output\Release.zip
       - store_artifacts:
          path: C:\Users\circleci\project\output\Release.zip
 